function J = Velocity_transformation(l1,l2,th1,th2)
%VELOCITY_TRANSFORMATION
%    J = VELOCITY_TRANSFORMATION(L1,L2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    21-Nov-2020 18:33:04

t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = l2.*t3;
t6 = l2.*t4;
t7 = -t5;
t8 = -t6;
J = reshape([t7-l1.*cos(th1),t8-l1.*sin(th1),0.0,t7,t8,0.0],[3,2]);
